# Generated by Django 3.2.13 on 2022-06-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novella', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
