# Generated by Django 3.2.13 on 2022-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novella', '0003_auto_20220615_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='describe',
            field=models.TextField(default='category text', max_length=200),
        ),
    ]
