# Generated by Django 3.2.13 on 2022-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novella', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_quote',
            field=models.TextField(default='Inspire_quotes', max_length=150),
        ),
    ]
