# Generated by Django 3.2.13 on 2022-06-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novella', '0006_profile_user_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_quote',
        ),
    ]
