# Generated by Django 3.2.13 on 2022-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novella', '0007_remove_profile_user_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
